### ISSUE TITLE
Question: What are some heuristic rules for initialization?

### ISSUE THREAD

**Issue by svilupp** [ReactiveBayes/RxInfer.jl#169]
It would be awesome to provide some simple tips for `initmessages` and `initmarginals` keywords in the `inference()`.

It was briefly covered [HERE](https://discourse.julialang.org/t/simple-linear-regression-with-reactivemp-rulemethoderror/81526/6), but it would be great to formalize the guidance a bit for people unfamiliar with the implementation.

**Comment by albertpod** [comment]
What's the status of this one?

**Comment by bvdmitri** [comment]
@Nimrais & @mhidalgoaraya 
This task has been added to the [milestone](https://github.com/biaslab/RxInfer.jl/milestone/4) for tracking and prioritization.

**Comment by Nimrais** [comment]
> What's the status of this one?

@albertpod, we had a discussion session with @mhidalgoaraya where we discussed several examples of situations where initialization is not necessary, and their counterparts where it is required. If I'm not mistaken, @mhidalgoaraya will prepare a Jupyter notebook or a markdown explanation.

**Comment by albertpod** [comment]
@mhidalgoaraya @Nimrais please update the ETA

**Comment by mhidalgoaraya** [comment]
@albertpod maybe I forgot to update but this was done several weeks ago, here it is the documentation https://reactivebayes.github.io/RxInfer.jl/stable/manuals/understanding-why-to-initialize-messages/
