### ISSUE TITLE
Examples need adjustments for new GraphPPL

### ISSUE THREAD

**Issue by bvdmitri** [ReactiveBayes/RxInfer.jl#242]
[Migration guide](https://reactivebayes.github.io/GraphPPL.jl/dev/migration_3_to_4/)

## Basic examples

- [x] Coin-Toss model (@raganapa, PR https://github.com/ReactiveBayes/RxInfer.jl/pull/267)
- [x] Bayesian Linear Regression (PR https://github.com/ReactiveBayes/RxInfer.jl/pull/243)
- [x] Kalman filtering and smoothing (@tonmalan https://github.com/ReactiveBayes/RxInfer.jl/pull/260)
- [x] Predicting Bike Rental Demand  (@albertpod, https://github.com/ReactiveBayes/RxInfer.jl/pull/258, Needs further improvements)
- [x] Hidden Markov Model (@Sepideh-Adamiat, https://github.com/ReactiveBayes/RxInfer.jl/pull/259)

## Advanced examples

- [x] Mountain car (@Sepideh-Adamiat, #264) 
- [x] Advanced Tutorial (@bvdmitri, https://github.com/ReactiveBayes/RxInfer.jl/pull/249)
- [x] People's skills (@carbonbasedsoul, https://github.com/ReactiveBayes/RxInfer.jl/pull/256)
- [x] Chance-constraints @Raphael-Tresor 
- [x] CVI (@albertpod, https://github.com/ReactiveBayes/RxInfer.jl/pull/258)
- [ ] Global parameter optimization (@abpolym)
- [x] GP by SDE (@HoangMHNguyen, https://github.com/ReactiveBayes/RxInfer.jl/pull/251) 
- [x] Infinite data stream (@Nimrais, https://github.com/ReactiveBayes/RxInfer.jl/pull/248)
- [x] Nonlinear sensor fusion (@Nimrais, https://github.com/ReactiveBayes/RxInfer.jl/pull/253)

## Problem specific

- [x] Autoregressive (@albertpod, https://github.com/ReactiveBayes/RxInfer.jl/pull/258)
- [x] Gamma mixture (@Nimrais, https://github.com/ReactiveBayes/RxInfer.jl/pull/254)
- [x] Gaussian mixture (@wouterwln, https://github.com/ReactiveBayes/RxInfer.jl/pull/250)
- [x] HGF (@bvdmitri, https://github.com/ReactiveBayes/RxInfer.jl/pull/255)
- [x] Invertible neural networks (@bartvanerp, https://github.com/ReactiveBayes/RxInfer.jl/pull/247)
- [x] Probit model (@Raphael-Tresor, https://github.com/ReactiveBayes/RxInfer.jl/pull/262)
- [x] RTS vs BIFM (@HoangMHNguyen, https://github.com/ReactiveBayes/RxInfer.jl/pull/252)
- [x] Simple nonlinear node (@abpolym, PR https://github.com/ReactiveBayes/RxInfer.jl/pull/270)
- [x] Universal mixtures (@bartvanerp, https://github.com/ReactiveBayes/RxInfer.jl/pull/246)

**Comment by Nimrais** [comment]
@bvdmitri, I would like to fix Infinite Data Stream and Gamma Mixture.

**Comment by HoangMHNguyen** [comment]
@bvdmitri I choose GPSDE and RTS vs BIFM

**Comment by wouterwln** [comment]
On the Mountain Car example @Sepideh-Adamiat , it might be worthy of a revision in general. The current example is, I think, an example of @ThijsvdLaar 's 2019 paper on "Simulating Active Inference Processes by Message Passing", and you can see the ideas of the paper explicitly named and coded as such. However, as an example of RxInfer, the main goal is not to demonstrate the ideas of a paper, but to demonstrate how to make an agent operate in a simple environment. Therefore I think we might need to adopt "standard" coding practices in the Mountain Car demo too (instead of creating a function that returns a callback function that reads/writes to global variables), to make clear what code specifically belongs to RxInfer and what code is just there to whip up the environment. Let me know what you guys think

**Comment by Raphael-Tresor** [comment]
@bvdmitri I would like to fix the 'Probit model' example and "Chance-constraints"

**Comment by mhidalgoaraya** [comment]
@bvdmitri  I choose the Kalman Filtering and Smoothing example

**Comment by albertpod** [comment]
@wouterwln as for Mountain Car. It's a great idea. We have more people interested in this particular example, but I agree that the way it's coded up isn't pretty. Mindful of that it needs to change, I am not sure what would be the best way. AFAIR, you had an implementation of this example with `RxEnvironments`. Could it be something to consider?

**Comment by Sepideh-Adamiat** [comment]
@wouterwln Regarding the mountain car example: I also agree that the current version is confusing and the coding should be improved. I can start working on that. I will try to make a PR in the upcoming weeks.

**Comment by bvdmitri** [comment]
Thanks everyone! It is super helpful! There is one example left, but I'm going to close the issue, as it becomes a bit difficult to manage different branches with different fixes together with the `examples` branch.
