### ISSUE TITLE
Documentation need adjustments for new GraphPPL.jl

### ISSUE THREAD

**Issue by bvdmitri** [ReactiveBayes/RxInfer.jl#257]
It is a tracking progress issue. I've started adjusting the documentation in a separate branch [#dev-4.0.0-documentatation](https://github.com/ReactiveBayes/RxInfer.jl/tree/dev-4.0.0-documentation).

- [x] Index (done by @bvdmitri, waiting for review)
- [x] README (done by @bvdmitri, waiting for review)

# Contributing section

- [x] New documentation (done by @bvdmitri, waiting for review)
- [x] New examples (done by @bvdmitri, waiting for review)
- [x] New package (done by @bvdmitri, waiting for review)
- [x] New release (done by @bvdmitri, waiting for review)
- [x] Overview (done by @bvdmitri, waiting for review)

# Library section

- [x] Bethe Free Energy (done by @bvdmitri, waiting for review)
- [x] Exported Methods (done by @bvdmitri, waiting for review)
- [x] Functional Forms (done by @bvdmitri, waiting for review)
- [x] Model Construction (done by @bvdmitri, waiting for review)

# Manuals 

- [x] Getting started (done by @bvdmitri, waiting for review)
- [x] Comparison (done by @bvdmitri, waiting for review)
- [x] Model specification (done by @bvdmitri, waiting for review)
- [x] Constraints specification (done by @bvdmitri, waiting for review)
- [x] Meta specification (done by @bvdmitri, waiting for review)
- [x] Custom Node (done by @bvdmitri, waiting for review)
- [x] Delta Node (done by @bvdmitri, waiting for review)
- [x] Debugging (done by @bvdmitri, waiting for review)

# Inference 

- [ ] Static Inference 
- [x] Streamlined inference (done by @bvdmitri, waiting for review)
- [x] Manual (removed entirely @bvdmitri, we don't want to support it anymore imo)
- [ ] Overview
- [x] Postprocess (done by @bvdmitri, waiting for review)

We also need a new section on migration from previous `RxInfer` to the new one.

- [x] Migration Guide

I may need your help @albertpod , @bartvanerp , @wouterwln with it. More structured request will be a bit later. If not changing, but at least reviewing. Let's make it a nicer release.

**Comment by bvdmitri** [comment]
@wouterwln I've updated the constraints specification documentation to my taste in this branch. Could you please check it out and merge it with https://github.com/ReactiveBayes/RxInfer.jl/pull/172 ?

**Comment by wouterwln** [comment]
@bvdmitri I did a revision of the contribution guide that's not reflected in this branch, is this on purpose or did we branch before I did the revision in main?

**Comment by bvdmitri** [comment]
@wouterwln I synced this branch with the `main`
