### ISSUE TITLE
Add documentation entry for `BetheFactorization` and `MeanField`

### ISSUE THREAD

**Issue by wouterwln** [ReactiveBayes/RxInfer.jl#288]
Currently we export these functionalities, but we don't seem to document them anywhere. I think adding them to the [documentation page on constraint specification](https://reactivebayes.github.io/RxInfer.jl/stable/manuals/constraints-specification/) is adequate

**Comment by bvdmitri** [comment]
Aren't they defined in GraphPPL? Maybe they should be documented there
