### ISSUE TITLE
missalignment in plot of example: examples/basic_examples/Coin Toss Model.ipynb?

### ISSUE THREAD

**Issue by juliusaka** [ReactiveBayes/RxInfer.jl#324]
Hi,
I'm trying to understand Bayesian Inference, which is why I look through your examples. In the above mentioned example,
examples/basic_examples/Coin Toss Model.ipynb,
The model is called for inference with
`model = coin_model(a=4.0, b = 8.0),`
while in the plot at the end the prior is plotted with,
`plot!(rθ, (x) -> pdf(Beta(2.0, 7.0), x), fillalpha=0.3, fillrange = 0, label="P(θ)", c=1,)`. 
Can you please clarifiy if that is a missalignment, or help me in my understanding?
Best,
Julius

**Comment by bvdmitri** [comment]
Good catch, @juliusaka! You're absolutely right—the `plot` should use the model's parameters. We likely overlooked this during the example refactoring. Could you prepare a pull request with the fix? It's a great way to contribute to RxInfer!

**Comment by mhidalgoaraya** [comment]
I am out of the office but for sure I take care of it next week.
