### ISSUE TITLE
Possible to get involved variables from functional form errors?

### ISSUE THREAD

**Issue by acertain** [ReactiveBayes/RxInfer.jl#335]
Hi, I'm trying out RxInfer and often running into `ERROR: `ProductOf` object cannot be used as a functional form in inference backend. Use form constraints to restrict the functional form of marginal posteriors.`. Is there any way to figure out which variables are involved in the ProductOf? As is I'm incrementally constructing a model to try to isolate variables, but it's pretty annoying.

**Comment by bvdmitri** [comment]
Agreed, this should be improved
