### ISSUE TITLE
Misleading mean-field constraint comment in HGF demo

### ISSUE THREAD

**Issue by albertpod** [ReactiveBayes/RxInfer.jl#383]
From what I can see, this HGF demo uses a mean-field factorization constraint:
```julia
@constraints function hgfconstraints() 
    # Structured factorization constraints
    q(x_next, x_prev, z_next) = q(x_next)q(x_prev)q(z_next)
end
```
Additionally, this notebook could be enhanced by adding an offline version of HGF where we construct a complete graph and set priors on the parameters of the GCV node, which appears to be supported according to the ReactiveMP.jl (https://github.com/ReactiveBayes/ReactiveMP.jl/tree/main/src/rules/gcv)."

**Comment by HoangMHNguyen** [comment]
I see, it's not structured-mean field. I'll fix that. For the additional enhancement, basically you want to implement a regular inference with HGF, if I understand correctly.

**Comment by albertpod** [comment]
For the first point, I would just change the naming to mean-field. As for the second bullet, yes, we just do a regular inference (smoothing) with additional priors on top of GCV node, aka kappa and omega.
